language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: AID6hR1hdYxWB+c2ISQlgktCvV+I4/KoalpgjERYZZYSjBlYEoBjBiJvkO0KLRFTd+gj4TFIkOodNCZYgOkQX7kslj+zSKSTm8qENVuXq5SdzGrjFWq0pHmWvMXE28H8/I1p2eiIzis3hd4Oduj+CoN9hg1LjqjzegS/Pzsnx2q7XBeF0Di4IBRXf2qGY621VXd39b96st2vOCaHUpWE3Kw1wT3oWlkr/cQGAwLXPcdxHCMEsI5AqPfMIMU0s9Hmz7fXCOKPwwOwtwC4aGEehlues+XQzss494Fi4tsfdMj5Gf72PRjlvOqhoEWlubpWDT6bYyUVOhZbEH7dD86E/aP8GXSg8I0KRLrSJ5kzFdmTKxCkf9fYy3BaNRrON2eFvHbSVX3GXsA843OS/4qdMUtHrs+na38Qe9rJzAqrudX0aFuKIBpJfmsFppCfKqmLr8syh7rc4b8tQRX0M0WwiDxTjinVj6Wtd9fq14DM2PbBJxHINy9fRjBdNbJHF0Qqtc1vEECl3vs7bzpa59AQlL4aN94PFpITdyR1f8VUuCAK8r16z431HeFsb767NbBtGAfe5brj8vvh1KaGV2Rh0081elIG1QyIS5EEclgDb0mMuEOJr9chygg6idvykDEzsEhhMaeoLR90DoCOv6YU4e16kRNMNwVoLSr5aqjn5xs=
  - secure: TUI+XrDrQBnJguEtuWWIPJX6YIx/xDvQbAf+KOlw+i7P5TdgfLMxu7YRxkCi0//tIvKlNB6vPway5JeWWEqqgoU9XHMbwh2CzfYbjE1KybjUi6vvkhaa2MEixIsAXJQVgWmxvlXIHu0aLpEVyxmTnY9DdwDHAijVcJCPvhRVNp2zGkMEB16Fom/ljChdn9d18IrqenI1ZBO5cx92daU9/lyGLPndiUou59owolKLqieRVfQpn2VKfGKzmb0Vnk+ghgOheNjGDh93SBNZvRT4F5B1fhGIwJgt599JUwe9RfEJiqFCldLwD/Djb6tMytmvkCQBmJK7THzpVD4Sa5pA1FKgI7YcQzBLGai/u52RBiS9kk67/5iSVhRe0Ml9wXUBJa+tyjejkOmWMAIbZ6kjip1uUQjqqAjd9dgZiR+f5F+wHp8fxU/wsV25/DerRDb9MKCpUtt//PS4uJP0kj53ympKJaVNy9YR53NN23Ez9I8RnKzzkzM3fr9HV1dVmiXzcUTTn4AkTKPOhC5jqOaV2id/e+jallS/IZPEETlwe5ugPBAjp1s3tLXbH4vdTlNm7tkDqHj8qBMk62AUQ+08ZnDE+eCmhKEut9f7hmYyLunsR79ErPAfrzv34koYKY+RLL5fPKCloeXWTrnCIunyw7zJZuBlVZgPUDbGOxj/7OA=
